### ISSUE TITLE
Attempting to put a simple item has space detector will cause server to crash and render that game unplayable

### ISSUE THREAD

**Issue by Flo2018v** [AlexIIL/SimplePipes#11]

**Comment by Flo2018v** [comment]
Oops accident’y closed it. Where can I send you a log?

**Comment by Flo2018v** [comment]
Update: I have tested it. Only happends when you use libblockattributes 1.4. Version 1.3.4 works

**Comment by AlexIIL** [comment]
This is likely because I haven't updated simple pipes to use libblockattributes 1.4.0 - however if you want to send a log you should be able to either attach it to a comment or upload it to https://gist.github.com ?

**Comment by EntranceJew** [comment]
I also experienced this, you can view the gist here: https://gist.github.com/EntranceJew/d0eed287c88e446bf5fc75b59943e471

(this is not from the initial crash but from loading a world afflicted by this issue)

Not sure if it's related but I can't seem to craft fluid tanks in survival worlds, I can only get them from the creative menu.

**Comment by AlexIIL** [comment]
This should be fixed now in simple pipes 0.1.5
