### ISSUE TITLE
No recipe for fluid tank

### ISSUE THREAD

**Issue by InfinitysDaughter** [AlexIIL/SimplePipes#16]
Love having the mod available but it seems the recipe for the basic fluid tank is missing. REI doesn't show anything and I tried using the original buildcraft recipe (8 glass) and it doesn't produce anything. I'm in 1.14.1 (v0.1.5).

**Comment by AlexIIL** [comment]
I've added one in 0.1.8:

|  | G  |  |
|--|--|--|
G | B | G
| | G | |

Where `G` is vanilla clear glass, and `B` is an empty bucket.
