### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Carnaxus** [AlexIIL/SimplePipes#17]
Crashlog: https://paste.ee/p/BMDUW

FabricLoader Game/mappings version 1.14.1 build 10, loader version 0.4.7 build 148
FabricAPI 0.3.0 prebuild 157a
SimplePipes 0.1.5

Also running:
Blockus 1.1.9.2
Don't Stub Your Toe 1.0.0 (for 1.14.1, I checked)
FabriBlocks 1.1.5

Halp?

**Comment by AlexIIL** [comment]
Have you downloaded `libblockattributes`? Currently simple pipes doesn't ship with it, so unfortunately you need to download it separately (https://minecraft.curseforge.com/projects/libblockattributes).

**Comment by Carnaxus** [comment]
Bah.  I can never remember to check the dependencies tab, and the main description doesn't actually say that LibBlockAttributes is _required_ so I didn't grab it.  Thanks :)

**Comment by AlexIIL** [comment]
> (From the curseforge page)
> This requires the fabric API!

Ok so at least that part is clear.
 
> This is primarily a mod to test implementations based on LibBlockAttributes, using...

Huh, yeah that is a lot less clear... thanks for pointing that out :D

**Comment by Carnaxus** [comment]
10/10 mod author response, would DL again :)
