### ISSUE TITLE
0.1.5: Pipes are invisible (only border box shown as wire frame)

### ISSUE THREAD

**Issue by Knito58** [AlexIIL/SimplePipes#18]
Fabric API 0.3.0-pre+build.167
MC 1.14.1 SP 0.1.5

The model of all pipes is invisible but the black wireframe lines show the size of the pipe when it was placed into the world. HWLA shows informations about the pipe and the GUI of the diamond pipe opens nicely - but I have no clue which colour points where.

**Comment by AlexIIL** [comment]
Can you add a full log file?

> but I have no clue which colour points where.

The colour is the same as the pipe in-world (if it was visible): so up is white, black is down, etc.

**Comment by Knito58** [comment]
https://pastebin.com/3VpG29vp

**Comment by Knito58** [comment]
I only found latest.log as it did not crash. Dunno where everything points to and remembered that the wooden pipe was the extraction pipe in buildcraft. This is the first time I use SimplePipes so there can be some misunderstanding on my side.

**Comment by AlexIIL** [comment]
Thanks. I'm not quite sure what causes it but I'll have a proper look when I port up to fabric 0.3.0, as fabric's new rendering hooks might be incompatible with my own changes.

**Comment by Knito58** [comment]
Thank you :)

**Comment by Knito58** [comment]
Meanwhile there is Fabric API build 180 but the pipes are still invisible. Is there anything I can do in my setup to render them visible? To have invisible pipes would be cool if they could be set invisible on purpose after the setup - and made visible again when fine tuning them further.
There is a pipe model that works: The "Energy Transfer Cable" of "Refined Machinery" is rendered nicely although that pipes do nothing more than connect blocks. But maybe you get some ideas from looking into the code.

https://github.com/NerdHubMC/Refined-Machinery

**Comment by Knito58** [comment]
![Invisible Iron Pipe](https://www.dropbox.com/s/9q012s0zuono7mb/simple_pipes_invisible.png) How and where to upload an image? My dropbox seems not to work anymore but I'm not willing to upgrade it to "pro" as it does not work.
[Maybe that works:](https://www.dropbox.com/s/9q012s0zuono7mb/simple_pipes_invisible.png?dl=0)

**Comment by AlexIIL** [comment]
I haven't started work on updating this yet, so I'm not surprised they are still invisible. (I primarily work on buildcraft, which I have updated privately to fabric 0.3.x, so I don't expect to come back to this for a little while).

> How and where to upload an image?

You should be able to drag + drop it in the github issue comment box?

**Comment by Knito58** [comment]
![simple_pipes_invisible](https://user-images.githubusercontent.com/2604989/59162985-9fdc9000-8afa-11e9-90db-10a6eac3a68b.png)
Thanks. Drag & Drop is way too easy - didn't get that in the last two years.
I'm very happy that the pipes are still alive.

**Comment by AlexIIL** [comment]
This should be fixed (fully) in 0.1.8

**Comment by Knito58** [comment]
Fix confirmed. And it works with the stockpile mod!
