### ISSUE TITLE
fabric.mod.json does not declare the LBA dependency

### ISSUE THREAD

**Issue by coderbot16** [AlexIIL/SimplePipes#21]
Just a minor enhancement for first-time downloading, this would make the error a more clear mod resolution issue instead of resulting in a NoClassDefFoundError.

**Comment by AlexIIL** [comment]
Ah, I see - SimplePipes uses "requires" rather than "depends" - I'm not sure if the format changed when it was made official or I just mistyped it the first time...

**Comment by coderbot16** [comment]
`requires` was part of the old schema but was also part of the example mod for a very long time, and a warning for it was only added recently. In any case, thanks for the quick fix! 👍
