### ISSUE TITLE
Upload newer version to your maven?

### ISSUE THREAD

**Issue by Fuyukai** [AlexIIL/SimplePipes#24]
I'd like to use this to test some of my stuff without having to implement my own pipes but it seems the newest version on your maven is from July which doesn't work with newer MC.

**Comment by AlexIIL** [comment]
I'm very close to releasing this newer version (at the same time as LBA 0.5.0, LNS, and LMP) so it should be up on my maven within a few days.

However if that's not good enough you might be able to build this for yourself and push it to your local maven (with `gradle clean build publishToMavenLocal`) on all 4 of the projects to use this.

**Comment by Fuyukai** [comment]
TIL about publishToMavenLocal.

**Comment by AlexIIL** [comment]
Ok, it should all be published now.
