### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by Yoghurt4C** [AlexIIL/SimplePipes#28]
is simplepipes on 19w46b(+) within the realm of possibility? just plopping the mod in as-is produces a[ completely unexpected, yet lengthy log](https://pastebin.com/gDMnp4bx)

**Comment by AlexIIL** [comment]
I'm not really interested in following snapshots, sorry

**Comment by AlexIIL** [comment]
(Mostly because I'm mostly developing buildcraft and I'd like some stability)

**Comment by Yoghurt4C** [comment]
understandable

**Comment by AlexIIL** [comment]
However I *am* interested in following pre-releases :p

**Comment by AlexIIL** [comment]
*(This depends on AlexIIL/LibMultiPart#7)*

**Comment by AlexIIL** [comment]
Ok, released as 0.3.1.
