### ISSUE TITLE
Golden Pipes and Diamond Pipes?

### ISSUE THREAD

**Issue by IZEDx** [AlexIIL/SimplePipes#3]
What about those two pipe types? Do they fit in this sample/basic repository or would you say they deserve a more broader transportation/mechanics mod?

I was trying out Simple Pipes yesterday on 19w13a and while I think the Contains Trigger is really neat, it still lacks an efficient way to sort stuff.

So yeah, I was thinking about getting into Minecraft Modding (look at my Profile, this usually is not my domain), forking this repo and adding them myself, but I'd first have to get started with this huge overhead so I thought I'd first poke around here to get what your priorities are with this. I think you could port them over from BuildCraft much much quicker than what it'd take me to get going with minecraft/fabric modding in the first place.

**Comment by AlexIIL** [comment]
The goal of this project was to test fabric to see how viable a buildcraft port to fabric is - nothing less and nothing more. (As I'm also the maintainer of @BuildCraft). So I don't really have a future plan for this project as I intend to either:

 - stop working on fabric entirely
 - port buildcraft itself to fabric.

So I'm fairly open to changes to this project, however I won't be continuing this for that much longer.
