### ISSUE TITLE
[1.15.2] Crash in REI Menu

### ISSUE THREAD

**Issue by Diamondman121314** [AlexIIL/SimplePipes#32]
From what I understand, when an item from SimplePipes shows up in REI, it crashes the client.
https://gist.githubusercontent.com/Cloak-Bot/c542ff660bc8f721365599c1b5908b50/raw/babf30fef3f56d97d82e248d7ab8e90b8561270c/crash.txt

**Comment by AlexIIL** [comment]
SimplePipes is built for 1.15.1, not 1.15.2. You'll either have to downgrade, or wait for me to [update](https://github.com/AlexIIL/SimplePipes/issues/33).
