### ISSUE TITLE
[MC 1.15.2 - SP 0.3.4] Possible Blocks Conflict

### ISSUE THREAD

**Issue by Dragonsissiy** [AlexIIL/SimplePipes#36]
Hello again! 

As I said on the mod page on curse, since installing this mod, it seems to conflict with Tech Reborn and Blockus in terms of shared blocks. (If I remember right from build craft they share some ores and in blockus's case, asphalt and a few others.) There are no crashes yet, but the ores from Tech Reborn are missing in the REI menu as well as in creative mode's menu. I'll list my entire mod list and the screenshots I took. I will also let the other mod owners know in case it ends up being a collaborative effort. I appreciate the time you take to work on these mods as I know you also have a life outside of minecraft. :3 Please let me know if there is anything else I can help with.

![CurrentModsList](https://user-images.githubusercontent.com/60621847/74001935-3aa79b80-4922-11ea-8b18-2cfa7dc52d24.PNG)

![LookingAtMCIron](https://user-images.githubusercontent.com/60621847/74001946-4dba6b80-4922-11ea-8005-a865d8ecc037.png)

![LookingAtTR_TinOre](https://user-images.githubusercontent.com/60621847/74001950-527f1f80-4922-11ea-8c85-9ca5144dac3e.png)

![LookingAtBlockus_Random](https://user-images.githubusercontent.com/60621847/74001959-58750080-4922-11ea-8023-552e617c6cf2.png)

![LookingAtBlockus_OrangeAsphalt](https://user-images.githubusercontent.com/60621847/74001967-5d39b480-4922-11ea-9089-6c8eeca1501e.png)

![LookingAtMenu_MissingBlocks](https://user-images.githubusercontent.com/60621847/74001983-69257680-4922-11ea-98e2-c5adfe9dea2a.png)

![LookingAtMenu_MissingBlockusBlocks](https://user-images.githubusercontent.com/60621847/74001989-6d519400-4922-11ea-91bd-a0e8aaf25266.png)

Thank you!

**Comment by Dragonsissiy** [comment]
Oh and only reason I even have the ores there, is because I already had them on my character on my server. When I search for them they no longer show up.

**Comment by Dragonsissiy** [comment]
Realized my REI was out of date, updated it to the most recent one v3.3.18 and still have the same issue.

**Comment by Dragonsissiy** [comment]
Just wanted to clarify that when Simple BC Pipes is not installed all other blocks from the other mods return.

**Comment by AlexIIL** [comment]
After some debugging it turns out this is an issue with how SimplePipes scans blocks for facades - essentially it scans the block just after it is registered (but before the item is registered)  and calls `Block.asItem()`, which then looks up the item to find... nothing. It then caches nothing for next time (woops) and then the correct item is registered.

**Comment by Dragonsissiy** [comment]
> After some debugging it turns out this is an issue with how SimplePipes scans blocks for facades - essentially it scans the block just after it is registered (but before the item is registered) and calls `Block.asItem()`, which then looks up the item to find... nothing. It then caches nothing for next time (woops) and then the correct item is registered.

I'm glad the issue has been found! I wish I understood more about modding to better help with my explanations lol. Thank you so much for looking into this so quickly. :D

**Comment by AlexIIL** [comment]
Ok, this has been fixed in 0.3.5.
