### ISSUE TITLE
Crash when Placing Wooden Pipe Next to Chest and flicking Lever

### ISSUE THREAD

**Issue by furtabs** [AlexIIL/SimplePipes#38]
https://hastebin.com/cerivelewa.sql

v 0.3.6

**Comment by AlexIIL** [comment]
As far as I can tell `LeverBlock` doesn't override `getPlacementState()`, so I think this is caused by another mods mixin. Can you enable mixin debugging by adding `-Dmixin.debug=true` to the JVM arguments of your launcher and uploading the full log?

**Comment by AlexIIL** [comment]
The crash report seems to have expired, so I can't look into this any more.
