### ISSUE TITLE
Server Crashing when destroying Tank Block

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [AlexIIL/SimplePipes#50]
When I destroy the simple fluid tank block it crashes.

<details>
  <summary>Spoiler: Crash Report</summary>
  
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2020-09-28 00:46:19 BST
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_1232
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.11)
    at alexiil.mc.lib.multipart.impl.MultipartBlock.afterBreak(MultipartBlock.java:401)
    at alexiil.mc.lib.multipart.impl.MultipartBlock.afterBreak(MultipartBlock.java:69)
    at net.minecraft.server.network.ServerPlayerInteractionManager.destroyBlock0(ServerPlayerInteractionManager:2222)
    at net.minecraft.server.network.ServerPlayerInteractionManager.handler$zkh000$destroyBlock(ServerPlayerInteractionManager:2196)
    at net.minecraft.server.network.ServerPlayerInteractionManager.tryBreakBlock(ServerPlayerInteractionManager:248)
    at net.minecraft.server.network.ServerPlayerInteractionManager.finishMining(ServerPlayerInteractionManager:222)
    at net.minecraft.server.network.ServerPlayerInteractionManager.processBlockBreakingAction(ServerPlayerInteractionManager:197)
    at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerAction(ServerPlayNetworkHandler:940)
    at net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.apply(PlayerActionC2SPacket:40)
    at net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.apply(PlayerActionC2SPacket:10)
    at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
    at net.minecraft.server.ServerTask.run(ServerTask:18)
    at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
    at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:758)
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:152)
    at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
    at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer:740)
    at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:734)
    at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127)
    at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer:719)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:671)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:254)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 4435125056 bytes (4229 MB) / 6417285120 bytes (6120 MB) up to 6442450944 bytes (6144 MB)
  CPUs: 6
  JVM Flags: 12 total; -Xms4G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
  Suspected Mods: LibMultiPart (libmultipart)
  Fabric Mods: autoconfig1u: Auto Config v1 Updated 3.2.2
               betternether: Better Nether 4.1.0
               byg: BYG 1.0.9
               campanion: Campanion 1.2.0+build.39
               cardinal-components-base: Cardinal Components API (base) 2.6.0
               cardinal-components-chunk: Cardinal Components API (chunks) 2.5.0
               cardinal-components-entity: Cardinal Components API (entities) 2.6.0
               cardinal-components-item: Cardinal Components API (items) 2.6.0
               cardinal-components-world: Cardinal Components API (worlds) 2.5.0
               cloth-api: Cloth API 1.2.1
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.1
               clothesline: Clothesline 0.3.0+1.16.3
               curios: Curios API 0.0.7-1.16.3
               endreborn: End: Rebellion 1.8
               extraalchemy: Extra Alchemy 1.3.0
               fabric: Fabric API 0.21.0+build.407-1.16
               fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
               fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad95
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+74685c1495
               fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd695
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.8.0+c1aa8ed895
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.5.0+c1aa8ed895
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e95
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e95
               fabricloader: Fabric Loader 0.9.3+build.207
               fenceplayerupper: Fence Player Upper 1.0.2+1.16.2
               fiber: fiber 0.23.0-1
               gravestones: Gravestones 1.5
               libblockattributes: LibBlockAttributes 0.8.1
               libblockattributes_core: LibBlockAttributes (Core) 0.8.1
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
               libblockattributes_items: LibBlockAttributes (Items) 0.8.1
               libcd: LibCapableData 3.0.2+1.16.2
               libmultipart: LibMultiPart 0.4.0
               libnetworkstack: Lib Network Stack 0.4.0
               library_of_exile: Library of Exile 1.0.4
               libstructure: LibStructure 1.5
               magna: Magna 1.4.2-1.16.2
               minecraft: Minecraft 1.16.3
               mmorpg: Age of Exile 1.3.12
               nbtcrafting: NBT Crafting 2.0.0-rc.6+mc1.16.2-pre1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               packed: Packed Storage 1.0.8
               patchouli: Patchouli 1.16.2-44-FABRIC
               phosphor: Phosphor 0.6.0+build.7
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.4.2+build.73
               roughlyenoughitems: Roughly Enough Items 5.4.2
               roughlyenoughitems-api: REI (API) 5.4.2
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.4.2
               roughlyenoughitems-runtime: REI (Runtime) 5.4.2
               rpgstats: RPGStats 2.3.2+1.16.3
               rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
               simple_pipes: SimplePipeTest 0.4.1
               simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.4.1
               staticdata: Static Data 1.1.2
               structure-helpers: Structure Helpers 3.0.0
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.5.4+build.122
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               vanilla-hammers: Vanilla Hammers 2.0.8-1.16.2
               vanillaexcavators: Vanilla Excavators 1.1.0
               waila: Hwyla 1.9.22
               whereisit: Where Is It 1.9
               xaerominimap: Xaero's Minimap 20.22.0
               xaeroworldmap: Xaero's World Map 1.10.3
  Player Count: 1 / 20; [class_3222['Tobi1Kenobi'/225, l='ServerLevel[Try]', x=-206.82, y=80.00, z=-161.58]]
  Data Packs: vanilla (incompatible), fabric/betternether, fabric/rpgstats, fabric/techreborn, fabric/fabric-tool-attribute-api-v1, fabric/structure-helpers, fabric/curios, fabric/endreborn, fabric/extraalchemy, fabric/libcd, fabric/vanilla-hammers, fabric/vanillaexcavators, fabric/mmorpg, fabric/campanion, fabric/clothesline (incompatible), fabric/fenceplayerupper, fabric/packed, fabric/gravestones, fabric/byg, fabric/simple_pipes
  Is Modded: Definitely; Server brand changed to 'fabric'
  Type: Dedicated Server (map_server.txt)

  
</details>

**Comment by AlexIIL** [comment]
It looks like 1.16.3 changed some things with how block loot dropping works internally so I'll need to update it to 1.16.3.

**Comment by AlexIIL** [comment]
Ok, this should now be fixed in [0.4.3](https://www.curseforge.com/minecraft/mc-mods/simplepipes/files/3101522)
