### ISSUE TITLE
Pipes not rendering.

### ISSUE THREAD

**Issue by dustojnikhummer** [AlexIIL/SimplePipes#52]
https://i.imgur.com/48DCOVf.png
Minecraft 1.16.5
Fabric 0.11.3
Fabric API 0.34.6
Mod version "simplepipes-all-0.5.0.jar"
Launcher: MultiMC 0.6.12

Modlist
https://i.imgur.com/IFk3ouz.png

PC Specs: AMD R5 5600H, Nvidia RTX 3060, 16GB RAM, Windows 10, Java jre1.8.0_291

**Comment by AlexIIL** [comment]
Sadly I don't think sodium is compatible with the fabric rendering API quite yet, so you'd need to remove it to make pipes visible. (See https://github.com/CaffeineMC/sodium-fabric/issues/5)

**Comment by dustojnikhummer** [comment]
> Sadly I don't think sodium is compatible with the fabric rendering API quite yet, so you'd need to remove it to make pipes visible. (See [CaffeineMC/sodium-fabric#5](https://github.com/CaffeineMC/sodium-fabric/issues/5))

Damn. I use Sodium to improve framerates when playing on my Switch. But yes, that fixed it.
